services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open_manipulator_ai_2
    tty: true
    restart: always
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
     - ROS_LOCALHOST_ONLY=0
    volumes:
      - /dev:/dev
      # - ./workspace:/workspace
      - ./workspace/start.sh:/workspace/start.sh
      - ./workspace/colcon_ws/src:/workspace/colcon_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    privileged: true
    command: bash -c 'chmod +x /workspace/start.sh && . /workspace/start.sh'
    #command: bash