name: ros-ci

on:
  push:
    branches: [  main, jazzy  ]
  pull_request:
    branches: [  main, jazzy  ]

jobs:
  ros2-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - jazzy
        include:
          - docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-jazzy-ros-base-latest
            ros_distribution: jazzy
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: ros_ws/src
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: open_manipulator
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
